version: '3'
services:
  plugin_store:
    build: .
    container_name: "${DEPLOYMENT_NAME}"
    environment:
        - DB_URL
        - ANNOUNCEMENT_WEBHOOK
        - SUBMIT_AUTH_KEY
        - B2_APP_KEY_ID
        - B2_APP_KEY
        - B2_BUCKET_ID
    networks:
        - plugins-network
    restart: unless-stopped

  redis_db:
    image: redis:latest
    restart: unless-stopped
    networks:
        - plugins-network
    environment:
        - REDIS_PORT=6379

  postgres_db:
    image: postgres:16 # Postgres databases are only compatible with their same major version
    restart: unless-stopped
    environment:
      - POSTGRES_DB=decky
      - POSTGRES_USER=decky
      - POSTGRES_PASSWORD
    networks:
        - plugins-network
    volumes: 
      - ${DB_PATH}:/var/lib/postgresql/data

networks:
  plugins-network:
    external: true
    driver: bridge
    name: caddy__bridge
