version: '3'
services:
  plugin_store:
    build: .
    container_name: plugin_store
    environment:
        - DB_URL
        - ANNOUNCEMENT_WEBHOOK
        - SUBMIT_AUTH_KEY=deadbeef
        - B2_APP_KEY_ID
        - B2_APP_KEY
        - B2_BUCKET_ID
    volumes:
        - .:/app
    restart: unless-stopped
    ports:
        - "5566:5566"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 5566

  redis_db:
    image: redis:latest
    restart: unless-stopped
    environment:
        - REDIS_PORT=6379

  postgres_db:
    image: postgres:16 # Postgres databases are only compatible with their same major version
    restart: unless-stopped
    environment:
      - POSTGRES_DB=decky
      - POSTGRES_USER=decky
      - POSTGRES_PASSWORD=decky
    volumes:
      - ../store-postgres:/var/lib/postgresql/data