name: Checks

on:
  pull_request:
  push:

defaults:
  run:
    working-directory: "/app"


jobs:
  build:
    uses: ./.github/workflows/build.yaml

  lint:
    runs-on: ubuntu-latest
    needs:
      - build
    container:
      image: ${{ needs.build.outputs.image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    strategy:
      matrix:
        linter: [flake8, isort, black, mypy]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - run: "make lint/${{ matrix.linter }}"

  test:
    runs-on: ubuntu-latest
    needs:
      - build
      - lint
    container:
      image: ${{ needs.build.outputs.image }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: "make test"
